# Generated by Django 6.0 on 2025-12-21 01:11

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_product_productimage_alter_category_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                        upload_to="admaker/stores/images/",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="ads_store_name_3a7a57_idx"),
                    models.Index(fields=["active"], name="ads_store_active_71747f_idx"),
                    models.Index(fields=["city"], name="ads_store_city_1cdd37_idx"),
                    models.Index(fields=["state"], name="ads_store_state_822eac_idx"),
                    models.Index(
                        fields=["active", "city", "state"],
                        name="ads_store_active_0de8bd_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ads_store_created_649f8a_idx"
                    ),
                ],
            },
        ),
    ]
