# Generated by Django 6.0 on 2025-12-21 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_store"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("published", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=120, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ads",
                        to="ads.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ads",
                        to="ads.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["active"], name="ads_ad_active_5e28b4_idx"),
                    models.Index(
                        fields=["published"], name="ads_ad_publish_ebbe9d_idx"
                    ),
                    models.Index(fields=["store"], name="ads_ad_store_i_6b12b8_idx"),
                    models.Index(fields=["product"], name="ads_ad_product_bf0162_idx"),
                    models.Index(
                        fields=["created_at"], name="ads_ad_created_9f5b83_idx"
                    ),
                    models.Index(
                        fields=["active", "published"], name="ads_ad_active_d92b2c_idx"
                    ),
                ],
            },
        ),
    ]
