# Generated by Django 6.0 on 2025-12-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_ad"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="sale_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["stock"], name="ads_product_stock_11a111_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["cost_price"], name="ads_product_cost_pr_c71fbe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["sale_price"], name="ads_product_sale_pr_5e4b57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["active", "category"], name="ads_product_active_f9d70c_idx"
            ),
        ),
    ]
